export default [
	{
		id: 337167,
		title: "Fifty Shades Freed",
		tagline: "Don't miss the climax",
		release_year: "2018",
		imgSrc: "https://image.tmdb.org/t/p/w500/3kcEGnYBHDeqmdYf8ZRbKdfmlUy.jpg",
		genres: ["Drama", "Romance"],
		runtime: 106,
	},
	{
		id: 269149,
		title: "Zootopia",
		tagline: "Welcome to the urban jungle.",
		release_year: "2016",
		imgSrc: "https://image.tmdb.org/t/p/w500/sM33SANp9z6rXW8Itn7NnG1GOEs.jpg",
		genres: ["Animation", "Adventure", "Family", "Comedy"],
		runtime: 108,
	},
	{
		id: 181808,
		title: "Star Wars: The Last Jedi",
		tagline: "The Saga Continues",
		release_year: "2017",
		imgSrc: "https://image.tmdb.org/t/p/w500/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg",
		genres: ["Fantasy", "Adventure", "Science Fiction"],
		runtime: 152,
	},
	{
		id: 284054,
		title: "Black Panther",
		tagline: "Long live the king",
		release_year: "2018",
		imgSrc: "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
		genres: ["Action", "Adventure", "Fantasy", "Science Fiction"],
		runtime: 134,
	},
	{
		id: 354912,
		title: "Coco",
		tagline: "The celebration of a lifetime",
		release_year: "2017",
		imgSrc: "https://image.tmdb.org/t/p/w500/eKi8dIrr8voobbaGzDpe8w0PVbC.jpg",
		genres: ["Adventure", "Comedy", "Family", "Animation"],
		runtime: 105,
	},
	{
		id: 333339,
		title: "Ready Player One",
		tagline: "A better reality awaits.",
		release_year: "2018",
		imgSrc: "https://image.tmdb.org/t/p/w500/pU1ULUq8D3iRxl1fdX2lZIzdHuI.jpg",
		genres: ["Adventure", "Science Fiction", "Action"],
		runtime: 140,
	},
	{
		id: 338970,
		title: "Tomb Raider",
		tagline: "Her legend begins",
		release_year: "2018",
		imgSrc: "https://image.tmdb.org/t/p/w500/ePyN2nX9t8SOl70eRW47Q29zUFO.jpg",
		genres: ["Action", "Adventure"],
		runtime: 118,
	},
	{
		id: 284053,
		title: "Thor: Ragnarok",
		tagline: "No Hammer. No Problem.",
		release_year: "2017",
		imgSrc: "https://image.tmdb.org/t/p/w500/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
		genres: ["Action", "Adventure", "Fantasy"],
		runtime: 130,
	},
	{
		id: 321612,
		title: "Beauty and the Beast",
		tagline: "Be our guest.",
		release_year: "2017",
		imgSrc: "https://image.tmdb.org/t/p/w500/tWqifoYuwLETmmasnGHO7xBjEtt.jpg",
		genres: ["Family", "Fantasy", "Romance"],
		runtime: 129,
	},
]
